name: getir_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^4.2.1
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # En son sürümü kontrol edin

flutter_icons:
  android: true
  ios: true
  image_path: "assets/getirAppIconImage/getirAppIcon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/getirAppIconImage/getirAppIcon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/advertImages/
    - assets/categoryImages/
    - assets/getirAppIconImage/
    - assets/navigationBarIcons/
    - assets/profileIconImages/